### ISSUE TITLE
Problems with the Dataset/Autotuner

### ISSUE THREAD

**Issue by SengaSacul** [crmclean/Autotuner#10]
Hi there,

hope your cruise went fine !

So Autotuner is running now, but there is an issue with the test data (beside there is no decription).
Pictures and resulting code attached as files :)

Could you maybe put up some more description on the GUI ?
Axes are not described.

A tutorial R Script would be great, for GUI and R only. I would appreciate any hint right know :)

Thank you !
Maybe Parameters are the same as in IPO, so I should get along that first ?

Best, Christina

![Error mmspData](https://user-images.githubusercontent.com/52703739/61409907-84c42380-a8e3-11e9-973d-0a6b7573d084.PNG)
[Error_Console.txt](https://github.com/crmclean/Autotuner/files/3403777/Error_Console.txt)
![Files_loaded](https://user-images.githubusercontent.com/52703739/61409938-93123f80-a8e3-11e9-92fd-988738a5832b.PNG)

**Comment by SengaSacul** [comment]
Short Trial:
`setwd("D:/R_Ordner/R_Autotuner/mmetspData/")

#Select Data Path (*.mzML)
data<-"D:/R_Ordner/R_Autotuner/mmetspData/mzMLs/"

#Select Meta Data File (*.csv)
meta<-read.csv2("mmetsp_metadata.csv", sep = ",")
#or
meta<-read.csv("mmetsp_metadata.csv", sep = ",", stringsAsFactors = F)
### both ending in the same problem

myAuto<-createAutotuner(data_paths = data, runfile = meta, file_col = meta$File.Name, factorCol = meta$Organism)

`

Ending with this:
`~~~ Autotuner: Initializator ~~~ 

~~~ Parsing Raw Data into R ~~~ 

Error in FUN(X[[i]], ...) : inherits(x, "mzR") is not TRUE
> `

**Comment by crmclean** [comment]
Hey Christina,

Thanks again for your feedback. I really appreciate you taking the time to help make AutoTuner more accessible once again. There is a tutorial R script titled Intro.Rmd within the vignette folder in this directory. Hopefully, that can help. 

I tried to reproduce your error on my console, and could not. At first, I thought the error might have to do with the path you entered into AutoTuner for the data, but that gave me a different error. Do you mind running the command session.info()? I'd like to see what version of the dependencies you've downloaded. 

A video showing off the GUI is on the way!

Craig

**Comment by SengaSacul** [comment]
So on the GUI this is the resulting code.
R is still busy, just taking more and more RAM. 

How long does "Find Peaks" normally take?

Listening on http://127.0.0.1:3559 ~~~ Autotuner: Initializator ~~~   ~~~ Parsing Raw Data into R ~~~   ~~~ Extracting the Raw Data from Individual Samples ~~~   ~~~ Storing Everything in Autotuner Object ~~~   ~~~ The Autotuner Object has been Created ~~~   Warning in eval(as.symbol(paste0("..", i))) :   restarting interrupted promise evaluation Warning: Error in <reactive>: no slot of name "peak_diff" for this object of class "Autotuner"   141: <reactive>   125: peakView   118: <reactive>   102: totalPeaks    97: renderUI    96: func    83: origRenderFunc    82: output$peakVisualization-plotCode     2: shiny::runApp     1: launchAutotuner
--
R still busy after 5 h :)

Aborting, Running Session Info:

sessionInfo() R version 3.6.1 (2019-07-05) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows 7 x64 (build 7601) Service Pack 1  Matrix products: default  locale: [1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 [4] LC_NUMERIC=C                           LC_TIME=English_United States.1252      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] shiny_1.3.2      mmetspData_0.1.0 Autotuner_0.1.0   loaded via a namespace (and not attached):   [1] colorspace_1.4-1             seqinr_3.4-5                 class_7.3-15                 modeltools_0.2-22              [5] mclust_5.4.5                 rprojroot_1.3-2              pls_2.7-1                    ggdendro_0.1-20                [9] fs_1.3.1                     rstudioapi_0.10              mzR_2.18.0                   remotes_2.1.0                 [13] affyio_1.54.0                flexmix_2.3-15               DT_0.7                       xml2_1.2.0                    [17] codetools_0.2-16             ncdf4_1.16.1                 doParallel_1.0.14            impute_1.58.0                 [21] robustbase_0.93-5            knitr_1.23                   ade4_1.7-13                  zeallot_0.1.0                 [25] pkgload_1.0.2                Formula_1.2-3                jsonlite_1.6                 Cairo_1.5-10                  [29] cluster_2.1.0                kernlab_0.9-27               vsn_3.52.0                   httr_1.4.0                    [33] BiocManager_1.30.4           readr_1.3.1                  compiler_3.6.1               PTXQC_0.92.6                  [37] backports_1.1.4              assertthat_0.2.1             lazyeval_0.2.2               limma_3.40.2                  [41] cli_1.1.0                    later_0.8.0                  htmltools_0.3.6              prettyunits_1.0.2             [45] tools_3.6.1                  gtable_0.3.0                 glue_1.3.1                   affy_1.62.0                   [49] reshape2_1.4.3               dplyr_0.8.3                  Rcpp_1.0.1                   MALDIquant_1.19.3             [53] Biobase_2.44.0               vctrs_0.2.0                  preprocessCore_1.46.0        iterators_1.0.10              [57] fpc_2.2-3                    crosstalk_1.0.0              stringr_1.4.0                xfun_0.8                      [61] proto_1.0.0                  ps_1.3.0                     rvest_0.3.4                  testthat_2.1.1                [65] mime_0.7                     devtools_2.1.0               XML_3.98-1.20                DEoptimR_1.0-8                [69] MASS_7.3-51.4                zlibbioc_1.30.0              zoo_1.8-6                    scales_1.0.0                  [73] MSnbase_2.10.1               kohonen_3.0.8                hms_0.5.0                    pcaMethods_1.76.0             [77] promises_1.0.1               ProtGenerics_1.16.0          parallel_3.6.1               sandwich_2.5-1                [81] RColorBrewer_1.1-2           yaml_2.2.0                   memoise_1.1.0                gridExtra_2.3                 [85] ggplot2_3.2.0                stringi_1.4.3                S4Vectors_0.22.0             desc_1.2.0                    [89] foreach_1.4.4                BiocGenerics_0.30.0          pkgbuild_1.0.3               BiocParallel_1.18.0           [93] rlang_0.4.0                  pkgconfig_2.0.2              prabclus_2.3-1               mzID_1.22.0                   [97] evaluate_0.14                lattice_0.20-38              purrr_0.3.2                  htmlwidgets_1.3              [101] processx_3.4.0               tidyselect_0.2.5             plyr_1.8.4                   ChemometricsWithR_0.1.13     [105] magrittr_1.5                 R6_2.4.0                     IRanges_2.18.1               pillar_1.4.2                 [109] withr_2.1.2                  BatchCorrMetabolomics_0.1.14 nnet_7.3-12                  tibble_2.1.3                 [113] crayon_1.3.4                 shinyFiles_0.7.3             crch_1.0-3                   rmarkdown_1.14               [117] usethis_1.5.1                grid_3.6.1                   data.table_1.12.2            callr_3.3.0                  [121] webshot_0.5.1                digest_0.6.20                diptest_0.75-7               xtable_1.8-4                 [125] httpuv_1.5.1                 scoringRules_0.9.6           stats4_3.6.1                 munsell_0.5.0                [129] viridisLite_0.3.0            kableExtra_1.1.0             sessioninfo_1.1.1
--
 
> | >
>

**Comment by crmclean** [comment]
Seems like the GUI is dealing with another separate issue. I'm sorry about that. Setting up a unit test for it has been a bit of a nightmare. Shiny usually keeps going even if the operation has halted, so that would explain the duration. 

In the meantime, maybe take a look at vignette and try running AutoTuner through the R command line instead. That's usually what I end up doing most of the time.

Thanks for posting the session info. I'll compare it with mine. Maybe that is what caused the inheritance error above.

**Comment by SengaSacul** [comment]
I tried just in R, using your script and that worked fine :)
So i'll try to mod that one.

With the GUI, I installed it on a second PC, a little bit different in Setup, same Issue. It keeps going.
Here comand line also works fine :)

**Comment by crmclean** [comment]
Glad to hear everything work well! This has been my first major software design project, so please work with me. I'll be happy to update and maintain the algorithm as you discover bugs. believe me when I say that I really appreciate your patience with this whole process. I'm going to close this out and create a new issue specific to the GUI.

**Comment by crmclean** [comment]
Glad to hear everything work well! This has been my first major software design project, so please work with me. I'm happy to update and maintain the algorithm as you discover bugs. Believe me when I say that I really appreciate your patience with this whole process. I'm going to close this out and create a new issue specific to the GUI.
