### ISSUE TITLE
Error in eicParamEsts Error in if (toowide || edge) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by SengaSacul** [crmclean/Autotuner#12]
Hi there, me again ... 

So now I tried my own data.
I checked with the sliding window analysis (5 samples) that small peaks were properly integrated.
lag <- 11
threshold<- 3.6
influence <- 0.2

It was a UPLC qTOF analysis, 25 biological replicates, so massTresh with 0.01 should be fine.

eicParamEsts <- EICparams(Autotuner = Autotuner, 
+                           massThresh = .01, 
+                           verbose = T,
+                           returnPpmPlots = F,
+                           useGap = T)
Currently on sample 1
--- Currently on peak: 1
-------- Number of bins detected with absolute mass error threshold: 14729
-------- Number of bins retained after checking that features within bins come from consecutive scans: 1307
-------- 8.9 % of bins retained after checking that features come from consecutive scans
-------- Number of bins with scans with 2+ mass observations: 60
-------- Number of ppm value across bins: 3017
-------- Number of ppm value across bins after KL Distance Filtering: 1508
Error in if (toowide || edge) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In findPeakWidth(approvScorePeaks = approvScorePeaks, mzDb = mzDb,  :
  NAs introduced by coercion

If I try a massTresh 0.001 it works for more than one sample, if I put it to 0.5 no match is found.
If I go to 0.25 Currently on sample 1

--- Currently on peak: 1
-------- Number of bins detected with absolute mass error threshold: 2
-------- Number of bins retained after checking that features within bins come from consecutive scans: 2
-------- 100 % of bins retained after checking that features come from consecutive scans
-------- Number of bins with scans with 2+ mass observations: 2
-------- Number of ppm value across bins: 36
Error in if (lowerBound < minScan) { : 
  missing value where TRUE/FALSE needed

I actually did not convert the data or recalibrate the data myself.
I guess the devil lies there ?
Any other issue?

**Comment by crmclean** [comment]
AutoTuner is doing a lot with the data on the backend. My guess is that you stumbled upon a corner case. Do you mind sharing 3-5 of your samples with me, so I can look into this more closely?

**Comment by SengaSacul** [comment]
Yes, I also have one other set, but there no TIC is visible and that one defenetly worked for XCMS :) Could you send me a mail to christina.lucas(at)uk-koeln.de? Then I can send you some raw files via gigshare...

**Comment by crmclean** [comment]
I was able to find fixes to both issues after receiving your data and have updated the package code. Thanks again for all your help!
