### ISSUE TITLE
Selection of the sliding window parameters.

### ISSUE THREAD

**Issue by hh1985** [crmclean/Autotuner#18]
Hi,

Just wonder how to automatically find the best `lag`, `threshold` and `influence` values.  
BTW, I cannot make Autotuner work with the `faahKO` example.

**Comment by crmclean** [comment]
Hi,

My apologies for not replying earlier. I did not see a notification from my email... I'll look into this to better serve you going forward.

The current design for AutoTuner does not feature anything like this. That being said, if you had ideas about algorithms that could identify chromatographic peak boundaries, maybe we could think about implementing something into the current version of the package. 

I previously tried to run faahKO. I found that the mass resolution of the data was not sufficient to apply AutoTuner and make accurate parameter estimates. I used the mtbls2 publicly available dataset within the vignette for this reason.

**Comment by andzajan** [comment]
Hi,

I haven't tried on faahKO data files, but I have noticed that extraction of EIC's sometimes fails if your data files are very different, e.g. some peaks are present only in few of mzML files. It also could be related to the RT shifts. I will investigate a little bit more and will provide a reproducible example.

**Comment by crmclean** [comment]
Hi @andzajan,

Please, do share the example. I appreciate you taking the time to help me improve the software. Could you please start a new issue in regards to it once you have it?

Craig
