### ISSUE TITLE
Error in plot_signals

### ISSUE THREAD

**Issue by pshahnazari** [crmclean/Autotuner#23]
Hi,
I have problem with factorCol and when I use this command :  plot_signals(Autotuner,  threshold, sample_index = 1:3, signals = signals), I am facing with this error:Error in plot_signals(Autotuner, threshold, sample_index = 1:3, signals = signals) : 
  factorCol is not within the MSest metadata.

**Comment by crmclean** [comment]
Good Afternoon,

This is pretty weird... Were you able to run the command createAutotuner prior to running plot_signals? Did this give you an error? The error indicates that the string containing the name of a column from your metadata was not found within the column names of the metadata. However, createAutotuner should have checked for the same thing.

**Comment by pshahnazari** [comment]
Hi,
Yes It looks weird. createAutotuner is: > Autotuner <- createAutotuner(rawPaths,                            metadata, file_col = "Raw.Spectral.Data.File", factorCol = "Factor.Value.genotype.")
~~~ Autotuner: Initializator ~~~ 

~~~ Parsing Raw Data into R ~~~ 

~~~ Extracting the Raw Data from Individual Samples ~~~ 

~~~ Storing Everything in Autotuner Object ~~~ 

~~~ The Autotuner Object has been Created ~~~ 

There isn't any error what I should do. Could you please find a solution I realy tend to run it.
Thank you

**Comment by crmclean** [comment]
I think the easiest way for me to solve the problem would be if I tried to recreate the issue on my computer. Could you please share 3 of your samples and the metadata spreadsheet with me?

**Comment by pshahnazari** [comment]
Hi again,
Sure
It is a big file I couldn't upload that I only mention the name of dataset form metabolight: MTBLS265
(Person01_blood_youth_POS.mzML, Person02_blood_youth_POS.mzML, Person03_blood_youth_POS.mzML)
Thank you

**Comment by crmclean** [comment]
Which file should I use for metadata?

**Comment by pshahnazari** [comment]
[a_mtbls265_POS_mass_spectrometry.txt](https://github.com/crmclean/Autotuner/files/4576923/a_mtbls265_POS_mass_spectrometry.txt)

**Comment by crmclean** [comment]
Awesome! Thanks! I'll try and have this fixed in the next few days.

**Comment by pshahnazari** [comment]
Thank you so much. I am looking forward to hearing from you

**Comment by crmclean** [comment]
Good Afternoon,

I think I identified the issue. I fixed a bug with checking the column names within createAutotuner. If you were to run createAutotuner, you should receive a similar error as what you are getting now.

So, how do you fix it? You are not providing the name of a column from your metadata into the argument factorCol. Try running the software again with a column name within your metadata. Please, do let me know if you have any issues.

**Comment by pshahnazari** [comment]
Good morning,
Thank you for your time but It is so weird. I have same error because I had inserted a column as factorCol and there is not any error for  createAutotuner again.
[a_mtbls265_POS_mass_spectrometry.txt](https://github.com/crmclean/Autotuner/files/4599242/a_mtbls265_POS_mass_spectrometry.txt)

**Comment by crmclean** [comment]
Good Morning,

You don't want to insert a column. You want to insert a string that contains the name of a column. Is this what you did? 

All the best,
Craig
