### ISSUE TITLE
Error: 'extract_peaks' is not an exported object

### ISSUE THREAD

**Issue by BaylorSci** [crmclean/Autotuner#24]
Hi
I have been trying to use your tool to compare to IPO optimisation for some data and have gotten study at the isolatePeaks step. In brief, when i run isolatePeaks, it returns the following message "No peaks were matched across samples. Consider asking extract_peaks to return more peaks.". However, when i try and use extract_peaks, it returns "Error: 'extract_peaks' is not an exported object from 'namespace:Autotuner" which is odd as it specifically is addressed in the R documentation.  Any help would be appreciated.

**Comment by crmclean** [comment]
Hi

Thanks for bringing up this issue! You have uncovered an error message from a previous version of AutoTuner. I have updated the code with a more coherent error message. To solve the error, please try to increase the value of the argument 'returned_peaks' from the function 'isolatePeaks.' 

All the best,
Craig

**Comment by BaylorSci** [comment]
Thanks for the quick response. That fixed the problem.
Separately, I also wonder whether you can shed some light on how you choose the lag, threshold and influence parameters? Is it just trial and error for the particular data using different combinations or is there a method to it using data from the scans?

**Comment by crmclean** [comment]
Hi

Glad things worked out. I bet you will not be the only person who will ask the second question. Why don't I close this issue out and address that question in a separate issue to make it easier for others to find that info in case they need it?
