### ISSUE TITLE
<0 rows> (or 0-length row.names) in metadata

### ISSUE THREAD

**Issue by pshahnazari** [crmclean/Autotuner#27]
Dear Craig,
Thank you very much indeed for your time and consideration about my problems in autotuner. I was dealing with another subject in last couple of weeks and when  I came back to autotuner I checked my codes line to line and  I found that my problem is in this code:
metadata <- metadata[sub("mzMLData/", "", metadata$Raw.Spectral.Data.File) %in% 
                       basename(rawPaths),]
**with <0 rows> (or 0-length row.names)**, how can I manage this problem I also as you recommend in previous issue,  I added factorCol as  
colnames<-("factorCol")
metadata$factorCol<-rownames(metadata)
Is it true?
Kind regards
Parisa

**Comment by crmclean** [comment]
Dear Parisa,

I apologize for the delay. A collaborate returned me some feedback on a paper around the time I received your issue. It seems like you are having issues using base R. Unfortunately those issues are beyond the scope of AutoTuner. 

I can recommend some resources. Specifically, this course which I used to learn R when I was first getting started:
https://www.coursera.org/learn/r-programming

All the best,
Craig

**Comment by pshahnazari** [comment]
Dear Craig, 

Thank you very much for your time and consideration 

Kind regards 

Parisa

> Dear Parisa, 
> 
> I apologize for the delay. A collaborate returned me some feedback on a paper around the time I received your issue. It seems like you are having issues using base R. Unfortunately those issues are beyond the scope of AutoTuner. 
> 
> I can recommend some resources. Specifically, this course which I used to learn R when I was first getting started:
> https://www.coursera.org/learn/r-programming 
> 
> All the best,
> Craig 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1]
https://github.com/crmclean/Autotuner/issues/27#issuecomment-643474088
[2]
