### ISSUE TITLE
Issues when using Autotuner with GC-MS data

### ISSUE THREAD

**Issue by FleurGaBru** [crmclean/Autotuner#28]
Hi Craig and all!

Do you have any experience in applying Autotuner to GC-MS data? We tried that but the results do not seem to make any sense. Could you give us any advise, if Autotuner could be applied for GC-MS at all and if so, how to tweak the parameters?

Thanks a lot in advance!

Our parameters for Autotuner were:

```
lag <- 25
threshold <- 4.1
influence <- 0.1
```

The results from Autotuner showed:
```
                 Parameters estimates Variability.Measure
ppm                     ppm    0.0000              0.0000
noise                 noise   11.7000              3.2070
preIntensity   preIntensity   41.4000             91.6000
preScan             preScan    2.0000              0.2582
snThresh           snThresh    3.0310              3.5590
Max Peakwidth Max Peakwidth    3.4900              0.4020
Min Peakwidth Min Peakwidth    0.4026              0.0000
                                                               Measure
ppm                            Standard Deviation of all PPM Estimates
noise                        Standard Deviation of all noise Estimates
preIntensity  Standard Deviation of all prefileter Intensity Estimates
preScan                 Standard Deviation of all scan coung Estimates
snThresh             Standard Deviation of all s/n threshold Estimates
Max Peakwidth       Distance between two highest estimated peak widths
Min Peakwidth        Distance between two lowest estimated peak widths

$ticParams
           descriptions estimates
max_width     max_width    4.2280
min_width     min_width    3.2210
group_diff   group_diff    0.9105
```

**Comment by crmclean** [comment]
Hi

Thanks for bringing up this concern. We did not build AT w/ GC-MS data in mind. That is not to say that it could not get it to pick parameters for GC data with a bit of tweaking. Do you mind sending me some of your data to play around with? I'm wondering if there is anything different about the structures between LC and GC data that is causing the error. 

All the best,
Craig

**Comment by FleurGaBru** [comment]
Hi Craig, thanks for your super fast response and enthousiasme to have a look at GC-MS data. I think it would be of so much value, if Autotuner would work for these kind of data, too. I will definitely send you data, but just have to sort out, which data from colleagues I can share with you. Is there anything specific you need? I could e.g. send you a file with the standard/calibration compounds. Would that make sense? Or do you prefer "real" samples from our untargeted measurements?

**Comment by crmclean** [comment]
Hi,

No problem. I am happy to help. Please send me three files that are replicates of one another. It doesn't really matter if these are standards or experimental samples. That should be sufficient to get started.

All the best,
Craig

**Comment by FleurGaBru** [comment]
Hi Craig! 

I have a dataset that I can share with you but I would prefer to send the downlink via email. Could you share your email with me, please? I made my email adres public in case you prefer to send me a message. Thanks!

**Comment by FleurGaBru** [comment]
Any news yet? :)

**Comment by crmclean** [comment]
Hi @FleurGaBru,

Hope you are doing well. I am closing this issue since we solved it a while ago through email.
