### ISSUE TITLE
Installation mmetspData Package not found

### ISSUE THREAD

**Issue by SengaSacul** [crmclean/Autotuner#9]
Hi there,

Using R 3.6.1 with RTools 3.5 installing via devtools does not work:

But I everytime fail to install, cause mmetspData can not be found.
I tried to find the package somewhere but its seems to be not available :)

Would be nice to test your tool :)

**Comment by crmclean** [comment]
Hey! 

Sorry for the delay in the reply, and thanks for bringing this issue to light. I'm on a research cruise at the moment. I will do my best to fix the issue you have brought forward.

**Comment by SengaSacul** [comment]
Thank you ! Have fun on the trip and save travels!

**Comment by crmclean** [comment]
Thank you for your patience. I've made an update to the README on how to install mmetspData. Please give that a shot and let me know if it works for you.

**Comment by SengaSacul** [comment]
Seems to work, installed it now! Thank you !
